"""
Unit tests for MetadataSignal.

Tests cover:
- JSON metadata with trusted keys (highest confidence path)
- JSON metadata with non-trusted keys (medium confidence path)
- Free-text pattern matching (medium confidence path)
- Various model patterns (OpenAI, Anthropic, Google, Meta, Mistral)
- Content with no model-identifying information (should return None)
- Edge cases: empty string, non-JSON string, nested JSON
"""

from __future__ import annotations

import json

import pytest

from whodidthis.signals.metadata import (
    CONFIDENCE_FREE_TEXT,
    CONFIDENCE_METADATA_FIELD,
    MetadataSignal,
)


@pytest.fixture
def signal() -> MetadataSignal:
    return MetadataSignal()


# ---------------------------------------------------------------------------
# JSON metadata — trusted key path (highest confidence)
# ---------------------------------------------------------------------------


class TestJsonTrustedKey:
    def test_model_field_gpt4(self, signal: MetadataSignal) -> None:
        content = json.dumps({"model": "gpt-4", "choices": [{"text": "Hello"}]})
        result = signal.analyze(content)
        assert result is not None
        assert result.model_attribution == "OpenAI GPT-4"
        assert result.confidence == CONFIDENCE_METADATA_FIELD
        assert result.signal_name == "metadata"
        assert result.evidence["source"] == "json_metadata_field"
        assert result.evidence["key"] == "model"

    def test_model_field_gpt4o(self, signal: MetadataSignal) -> None:
        content = json.dumps({"model": "gpt-4o"})
        result = signal.analyze(content)
        assert result is not None
        assert result.model_attribution == "OpenAI GPT-4o"
        assert result.confidence == CONFIDENCE_METADATA_FIELD

    def test_model_field_gemini(self, signal: MetadataSignal) -> None:
        content = json.dumps({"model": "gemini-1.5-pro"})
        result = signal.analyze(content)
        assert result is not None
        assert result.model_attribution == "Google Gemini"
        assert result.confidence == CONFIDENCE_METADATA_FIELD

    def test_engine_field_gpt35(self, signal: MetadataSignal) -> None:
        content = json.dumps({"engine": "gpt-3.5-turbo", "usage": {}})
        result = signal.analyze(content)
        assert result is not None
        assert result.model_attribution == "OpenAI GPT-3.5"
        assert result.confidence == CONFIDENCE_METADATA_FIELD
        assert result.evidence["key"] == "engine"

    def test_model_name_field(self, signal: MetadataSignal) -> None:
        content = json.dumps({"model_name": "claude-3-sonnet"})
        result = signal.analyze(content)
        assert result is not None
        assert result.model_attribution == "Anthropic Claude 3"
        assert result.confidence == CONFIDENCE_METADATA_FIELD

    def test_generator_field(self, signal: MetadataSignal) -> None:
        content = json.dumps({"generator": "llama-3", "version": "1.0"})
        result = signal.analyze(content)
        assert result is not None
        assert result.model_attribution == "Meta LLaMA 3"
        assert result.confidence == CONFIDENCE_METADATA_FIELD

    def test_nested_model_field(self, signal: MetadataSignal) -> None:
        """Model field one level deep in JSON is also inspected."""
        content = json.dumps({"response": {"model": "mistral-large", "tokens": 100}})
        result = signal.analyze(content)
        assert result is not None
        assert result.model_attribution == "Mistral AI"
        assert result.confidence == CONFIDENCE_METADATA_FIELD

    def test_model_field_claude2(self, signal: MetadataSignal) -> None:
        content = json.dumps({"model": "claude-2.1"})
        result = signal.analyze(content)
        assert result is not None
        assert result.model_attribution == "Anthropic Claude 2"

    def test_model_field_llama2(self, signal: MetadataSignal) -> None:
        content = json.dumps({"model": "llama-2-70b"})
        result = signal.analyze(content)
        assert result is not None
        assert result.model_attribution == "Meta LLaMA 2"


# ---------------------------------------------------------------------------
# JSON metadata — non-trusted key path (lower confidence)
# ---------------------------------------------------------------------------


class TestJsonNonTrustedKey:
    def test_non_trusted_key_with_model_name(self, signal: MetadataSignal) -> None:
        content = json.dumps({"response_generated_by": "gpt-4"})
        result = signal.analyze(content)
        assert result is not None
        assert result.model_attribution == "OpenAI GPT-4"
        assert result.confidence == CONFIDENCE_FREE_TEXT

    def test_description_field(self, signal: MetadataSignal) -> None:
        content = json.dumps({"description": "Generated by Claude-3-Opus"})
        result = signal.analyze(content)
        assert result is not None
        assert result.model_attribution == "Anthropic Claude 3"
        assert result.confidence == CONFIDENCE_FREE_TEXT


# ---------------------------------------------------------------------------
# Free-text pattern matching
# ---------------------------------------------------------------------------


class TestFreeText:
    def test_gpt4_in_text(self, signal: MetadataSignal) -> None:
        content = "This document was produced using GPT-4 for summarization."
        result = signal.analyze(content)
        assert result is not None
        assert result.model_attribution == "OpenAI GPT-4"
        assert result.confidence == CONFIDENCE_FREE_TEXT
        assert result.evidence["source"] == "free_text"

    def test_gemini_in_text(self, signal: MetadataSignal) -> None:
        content = "The response was generated by Gemini Pro."
        result = signal.analyze(content)
        assert result is not None
        assert result.model_attribution == "Google Gemini"

    def test_claude_in_text(self, signal: MetadataSignal) -> None:
        content = "Powered by Claude from Anthropic."
        result = signal.analyze(content)
        assert result is not None
        assert result.model_attribution == "Anthropic Claude"

    def test_mistral_in_text(self, signal: MetadataSignal) -> None:
        content = "Using Mistral-7B for local inference."
        result = signal.analyze(content)
        assert result is not None
        assert result.model_attribution == "Mistral AI"

    def test_case_insensitive(self, signal: MetadataSignal) -> None:
        content = "output from GEMINI-FLASH"
        result = signal.analyze(content)
        assert result is not None
        assert result.model_attribution == "Google Gemini"

    def test_matched_text_in_evidence(self, signal: MetadataSignal) -> None:
        content = "This text was produced by gpt-4o."
        result = signal.analyze(content)
        assert result is not None
        assert "matched_text" in result.evidence
        assert "gpt-4o" in result.evidence["matched_text"].lower()  # type: ignore[operator]


# ---------------------------------------------------------------------------
# No match — should return None
# ---------------------------------------------------------------------------


class TestNoMatch:
    def test_plain_human_text(self, signal: MetadataSignal) -> None:
        content = "The quick brown fox jumps over the lazy dog."
        result = signal.analyze(content)
        assert result is None

    def test_empty_string(self, signal: MetadataSignal) -> None:
        result = signal.analyze("")
        assert result is None

    def test_json_without_model_info(self, signal: MetadataSignal) -> None:
        content = json.dumps({"name": "Alice", "age": 30, "city": "Paris"})
        result = signal.analyze(content)
        assert result is None

    def test_json_with_non_string_values(self, signal: MetadataSignal) -> None:
        content = json.dumps({"count": 42, "active": True, "data": [1, 2, 3]})
        result = signal.analyze(content)
        assert result is None

    def test_non_json_string(self, signal: MetadataSignal) -> None:
        content = "not json at all {broken"
        result = signal.analyze(content)
        assert result is None

    def test_json_list_root(self, signal: MetadataSignal) -> None:
        """JSON root that is a list (not a dict) should fall through to free-text."""
        content = json.dumps(["a", "b", "c"])
        result = signal.analyze(content)
        assert result is None


# ---------------------------------------------------------------------------
# Signal metadata
# ---------------------------------------------------------------------------


class TestSignalMetadata:
    def test_name(self, signal: MetadataSignal) -> None:
        assert signal.name == "metadata"

    def test_priority(self, signal: MetadataSignal) -> None:
        assert signal.priority == 10

    def test_repr(self, signal: MetadataSignal) -> None:
        r = repr(signal)
        assert "MetadataSignal" in r
        assert "metadata" in r


# ---------------------------------------------------------------------------
# SignalResult validation
# ---------------------------------------------------------------------------


class TestSignalResultValidation:
    def test_result_confidence_in_range(self, signal: MetadataSignal) -> None:
        content = json.dumps({"model": "gpt-4"})
        result = signal.analyze(content)
        assert result is not None
        assert 0.0 <= result.confidence <= 1.0

    def test_result_has_evidence(self, signal: MetadataSignal) -> None:
        content = json.dumps({"model": "gpt-4"})
        result = signal.analyze(content)
        assert result is not None
        assert isinstance(result.evidence, dict)
        assert len(result.evidence) > 0
